### ISSUE TITLE
Duration is NaN on some movies

### ISSUE THREAD

**Issue by silverqx** [bartholomej/node-csfd-api#11]
Eg. [Lord of the rings](https://www.csfd.cz/film/4711-pan-prstenu-spolecenstvo-prstenu/recenze/) movies have special Length, they have three types of length, normal, directors cut, and special edition. In this case, the duration is NaN.

```js
λ node .\index.js csfd-get 4711 -r
{
  id: 4711,
  title: 'Pán prstenů: Společenstvo Prstenu',
  year: 2001,
  duration: NaN,
  descriptions: [
```

**Comment by bartholomej** [comment]
Hi @silverqx,
I've improved the movie length detection. Check if it works for you.
The tests run specifically against the movie you posted (Lord of the Rings), but please try it with more movies and TV shows.

You can use the `next` version
```bash
npm install node-csfd-api@next
```
Make sure you have version `2.1.0-next.1` (or later) installed.

Let me know ;)

**Comment by silverqx** [comment]
Thx, I test and let know. 👌

**Comment by silverqx** [comment]
I have tested it on a few movies and it looks good.
