### ISSUE TITLE
imdb id in movie detail

### ISSUE THREAD

**Issue by silverqx** [bartholomej/node-csfd-api#12]
Would be possible to add IMDb id into the movie detail?

**Comment by bartholomej** [comment]
I know it would be great, but unfortunately ČSFD doesn't provide information about IMDB id. 
Well, it does, but only for logged in users.

Try opening some movie detail as **logged in** and **not logged in** user. 

There you will see what I am talking about :/

**Comment by silverqx** [comment]
These are not good news ☹️, but it is as you wrote for logged users only, they have to change it because on the old čsfd the imdb id was provided, it was also provided in the [csfd-api](https://www.npmjs.com/package/csfd-api) node package and I used it in my code.

I will have to remove it ☹️, but it is what it is.

**Comment by silverqx** [comment]
I also looked to the csfd html source code whether by chance this id is not hidden somewhere and isn't, I think we can close this if you don't know about another way how to obtain it.

**Comment by bartholomej** [comment]
Yes. I've tried it too, and unfortunately there's no information about IMDB id :/

I guess we will close this issue now.

**Comment by 1ucay** [comment]
Hello, I have SQL with cross of IMDB => CSFD vica versa..
https://ulozto.cz/file/dmbIAsLzB37N/imdb-2022-11-12-18-19-38-sql-gz#!ZGWuAGR1LJV3LmL2MTZ3LJWvAGH5GwpmDycLFKc+pHgRZwAy

**Comment by bartholomej** [comment]
Great job! But I won't intergrate it into the app, because it has several megabytes and it is not that useful for everyone :(

Unless you (or someone) expose some separate service (rest API) to get these ids.

In this library it would then be called like this _(only proposal)_:
```ts
csfd.movie(12345, {withImdb: true}).then(x => console.log(x));
```

**Comment by 1ucay** [comment]
Ok I undestand, but it can be done over csv file, which has 9MB :)

**Comment by bartholomej** [comment]
Yes, but still... I don't want to provide several MBs library just for this feature.
Let's keep it small :)
But if there will be some small stable service (rest/graphql) with this IDs mapping, I will be happy to create this feature for you ;)

**Comment by 1ucay** [comment]
I dont need it, I have personal solution for Emby/jellyfin.
