### ISSUE TITLE
empty descriptions array in movie detail

### ISSUE THREAD

**Issue by silverqx** [bartholomej/node-csfd-api#14]
When movie has more descriptions like [Ironclad](https://www.csfd.cz/film/266501-templar/recenze/) or [Matrix Resurrections](https://www.csfd.cz/film/499395-the-matrix-resurrections/recenze/) then descriptions array is empty.

Movies with one description work good and I didn't find any movies with 3 or more descriptions so I can't tell about this case.

**Comment by bartholomej** [comment]
Should be fixed in version `v2.1.1-next.0` ;)

As always you can try it like this:
```bash
npm install node-csfd-api@next
```

Make sure you have `v2.1.1-next.0` (or later) installed.

**Comment by silverqx** [comment]
Now its clear, thx for clarification 😎

**Comment by bartholomej** [comment]
[v2.2.0 stable](https://github.com/bartholomej/node-csfd-api/releases/tag/v2.2.0) released 🎉  Thx
