### ISSUE TITLE
Feature request: Add number of ratings

### ISSUE THREAD

**Issue by iljapanic** [bartholomej/node-csfd-api#9]
Thanks for a wonderful library. I've just used it to successfully deploy a super simple API endpoint on Heroku to use with my personal movie database.

I was wondering if would consider also adding information about the **number of ratings**?

The API already returns the calculated percentage, but the number of ratings helps you better determine the relevance/significance of the rating.

I looked through your code and considered making a pull request. Unfortunately, I can't write tests and I don't think my code would be up to your standards. Hopefully, it should be quite simple to scrape the information.

Here is the element in question:

```
<span class="counter">**{NUMBER OF RATINGS}**</span>
```

![CleanShot 2021-11-16 at 19 27 44@2x](https://user-images.githubusercontent.com/1295321/142044155-af98bb06-49b5-43fa-aab9-094e2a0d4158.png)

**Comment by bartholomej** [comment]
Hi Ilja, thanks for the suggestion. 
You are right, this property is interesting and was missing here.

So the new version 1.8.0 already includes `ratingCount`

Let me know how it works ;)

_If you're interested in how it's done, you can look at the pull request ;) #10_

**Comment by iljapanic** [comment]
Wow, that was super fast. I've just deployed the updated version to Heroku and it works great. Thank you! 🙏
